# Generated by Django 4.1.7 on 2023-03-14 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='reting',
            new_name='rating',
        ),
    ]
